### ISSUE TITLE
Multilanguage GUI

### ISSUE THREAD

**Issue by bovirus** [euzzeud/GetWindows11Utility#1]
@euzzeud 

Could you please consider to modify teh source to have a multilanguage GUI?

**Comment by euzzeud** [comment]
Hello ! For the moment the iso file I get are only available in English ... You can always (I think) add a system display language in the settings.
**Parameters > Time & Language > Language**
Screenshot:
[https://ibb.co/BN8N1P3](https://ibb.co/BN8N1P3)

**Comment by bovirus** [comment]
@euzzeud

I think abouit your program GUI multilangauge (not O.S:).

**Comment by euzzeud** [comment]
Okay😅! It is true that it could be interesting... Thanks for the suggestion, I will see how to do it.

**Comment by bovirus** [comment]
@euzzeud 

It should bit simply.
All strings are in

https://github.com/euzzeud/GetWindows11Utility/blob/main/GetWindows11/GetWindows11/Form1.resx

Thanks.
