### ISSUE TITLE
I get this error: Can't find the URL of the ISO on the server!

### ISSUE THREAD

**Issue by nisamo** [euzzeud/GetWindows11Utility#2]
When start program and Press Download ISO get this error:

I get this error: Can't find the URL of the ISO on the server!

**Comment by euzzeud** [comment]
Hello ! When did download the app exe file? Because if the download goes back more than 5h, please download it again and try to download the iso file with the new version of the utility exe file (in witch the problem is fixed). If the problem persists, recontact me.

**Comment by nisamo** [comment]
Hello, Fixed with Download again program
