### ISSUE TITLE
Download does not work

### ISSUE THREAD

**Issue by shmshd** [euzzeud/GetWindows11Utility#3]
Hi,

With on click of download, it just downloads the HTML source page of Media Fire to Windows_11.iso.

I guess your Media Fire key for the direct download is expired or changed.

Link from Gdrive text file: https://download1477.mediafire.com/gcrtkmec7w3g/em6mh6kupe51ggx/Windows_11_22000.1.210604-1628.CO_RELEASE_CLIENTMULTI_X64FRE_EN-US.ISO

![image](https://user-images.githubusercontent.com/11484121/124558939-2dab1680-de4c-11eb-98c1-80e94aac23dd.png)

Downloaded file: 
[Windows_11.zip](https://github.com/euzzeud/GetWindows11Utility/files/6768072/Windows_11.zip)

**Comment by euzzeud** [comment]
Oh ok... it is mediafire which blocks the links after a moment... I solve the problem in the afternoon and I will get back to you. Thanks for reporting!

**Comment by euzzeud** [comment]
Its good. I changed the MediaFire link. You can now try again.

**Comment by shmshd** [comment]
@euzzeud tried now, still the same. I guess you will have to ditch Media Fire.

**Comment by euzzeud** [comment]
Yes, I put back the ISO of the leak build (which was on a webserver) while waiting to find a solution to host the next builds (because I do not have a webserver). If you have a solution or an idea, I'm interested!

**Comment by euzzeud** [comment]
I could host it on Google Drive but there is a virus check that fails, it returns to a web page with a confirmation button to download and therefore the program will download this web page instead of the desired file.
